export { Faple } from './faple.mjs'
export { type FapleImpl } from './fapleImpl/fapleImpl.mjs'
export { Component } from './component/component.mjs'
export { Comp } from './decorator/component.mjs'
export { Reactive } from './decorator/reactive.mjs'
// export { Watch } from './decorator/watch'
export { Bind } from './decorator/bind.mjs'
export type { VNodeInstanceRoot, VNodeElement } from './vdom/vnode.mjs'
export { createReference } from './vdom/vnode.mjs'
export type { Reference } from './vdom/vnode.mjs'
export * from './constant.mjs'