export { Faple } from './faple'
export { Component } from './component/component'
export { Comp } from './decorator/component'
export { Reactive } from './decorator/reactive'
export { Watch } from './decorator/watch'
export { Bind } from './decorator/bind'
export type { VNodeInstanceRoot } from './vdom/vnode'
export { createReference } from './vdom/vnode'
export type { Reference } from './vdom/vnode'
export * from './constant'